# Site settings
title: 재팍의 개발 블로그
name: Jaehyun Park # your name
email: jaeepark@gmail.com # your email address
description: >
     자바 백앤드 개발을 공부하면서 배운점과 여러 생각을 기록하는 블로그 입니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: # your Twitter username
github_username: krapeaj # your Github username
disqus_username: # your disqus username

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/pages/:num/"

exclude:
  - README.markdown

google-analytics: # add it if you have one

skillstree: false # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
