# Site settings
title: Dukki Hong
name: Dukki Hong # your name
email: ghd7262@gmail.com # your email address
description: >
     Data Enthusiast.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: # your Twitter username
github_username: ghd7262 # your Github username
disqus_username: # your disqus username

plugins:
  - jekyll-paginate

# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# paginate: 5
# paginate_path: "/pages/:num/"

exclude:
  - README.markdown

google-analytics: # add it if you have one

skillstree: false # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
